### ISSUE TITLE
Error in getting user information

### ISSUE THREAD

**Issue by pavi2410** [bartholomej/instagram-scraper-api#10]
```
TypeError: Cannot read property '0' of undefined
    at getUserData (/home/runner/sociorank/node_modules/instagram-scraper-api/helpers/user.helper.js:19:152)
    at InstagramScraper.user (/home/runner/sociorank/node_modules/instagram-scraper-api/index.js:12:46)
```

**Comment by pavi2410** [comment]
```js
instagram.userScraper.user(username).then(data => {
  console.log(data.entry_data)
})
```
returns
```
{
  LoginAndSignupPage: [
    {
      captcha: [Object],
      gdpr_required: false,
      tos_version: 'row',
      username_hint: ''
    }
  ]
}
```

There is no `ProfilePage` property present.

**Comment by bartholomej** [comment]
hi @pavi2410, I'm afraid instagram is now testing a feature where [it stops showing user profiles without logging](https://thenextweb.com/news/instagram-now-forces-people-to-sign-in-to-view-public-profiles) in, so the script may not see the profile at all.

Try opening some user's profile on instagram.com (in anonymous browser mode). If it forces you to log in, then this script can't work anymore :( 

Let me know.

**Comment by pavi2410** [comment]
Yup, I tried every possible way to scrape without authentication, but nothings seems to work. I have also found that the requests must be made in proximity to the user's current location. Not knowing that fact, I wasted a lot of time.

**Comment by N0nick1597** [comment]
Maybe someone found the way to login and use this code with it?

**Comment by gurubobnz** [comment]
We're using this https://github.com/pgrimaud/instagram-user-feed which supports fetching after login, but even then we're finding that Instagram catches up with us and blocks the IP we are accessing the info from. Until Instagram supports this natively we're going to be playing a chasing game trying to pretend we're all web browsers and real people :(
